name: Bitbake (kirkstone)

on:
  push:
    branches:
      - kirkstone
  pull_request:
    branches:
      - kirkstone

jobs:
  build:
    strategy:
      matrix:
        recipe: [openjdk-8-jre, openjdk-11-jre, openjdk-17-jre, openjdk-21-jre]
        machine: [qemuarm, qemuarm64, qemux86-64]
      max-parallel: 3
    runs-on: ubuntu-latest
    steps:
      - name: Install software required by OpenEmbedded
        run: |
          sudo apt-get update
          sudo apt-get install gawk wget git diffstat unzip texinfo \
            gcc build-essential chrpath socat cpio python3 python3-pip \
            python3-pexpect xz-utils debianutils iputils-ping python3-git \
            python3-jinja2 libegl1-mesa libsdl1.2-dev xterm \
            python3-subunit mesa-common-dev zstd liblz4-tool
      - name: Checkout OE-Core
        uses: actions/checkout@v3
        with:
          repository: openembedded/openembedded-core
          ref: kirkstone
          path: oe-core
      - name: Checkout Bitbake
        uses: actions/checkout@v3
        with:
          repository: openembedded/bitbake
          ref: '2.0'
          path: oe-core/bitbake
      - name: Checkout sources of this project
        uses: actions/checkout@v3
        with:
          path: oe-core/meta-openjdk-temurin
      - name: Replace config of build-environment
        run: |
          cd oe-core
          source oe-init-build-env build > /dev/null 2>&1
          mv -v ../meta-openjdk-temurin/.github/workflows/bitbake-kirkstone-local.conf \
            conf/local.conf
      - name: Add layer to build-environment
        run: |
          cd oe-core
          source oe-init-build-env build > /dev/null 2>&1
          bitbake-layers add-layer ../meta-openjdk-temurin
      - name: Restore cached sstate of Bitbake
        id: cache-bitbake-sstate-restore
        uses: actions/cache/restore@v3
        with:
          path: oe-core/build/sstate-cache
          key: bitbake-sstate_kirkstone_${{ matrix.machine }}
      - name: Build ${{ matrix.recipe }} with Bitbake
        run: |
          cd oe-core
          source oe-init-build-env build > /dev/null 2>&1
          MACHINE=${{ matrix.machine }} bitbake ${{ matrix.recipe }}
      - name: Save sstate of Bitbake
        id: cache-bitbake-sstate-save
        if: steps.cache-bitbake-sstate-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: oe-core/build/sstate-cache
          key: ${{ steps.cache-bitbake-sstate-restore.outputs.cache-primary-key }}
